accessKeyId and secretKey are optional. fixed AWS SDK promisify bug
jsreport/jsreport-fs-store-aws-s3-persistence pull request #5
Opened 2019-05-16 07:19 UTC by cachenbach

I changed a little bit the way the accessKeyId and secretKey are used. Before both were mandatory for S3 but were not used for SQS. In my version both are optional for S3 and SQS. So, you so can use a AWS Role for the Lambda and don't need to use the keys. But you can use them, if you work locally. 

A newer version of the AWS SDK was used, but this version has problem with Promise.promisifyAll(): 
`Error occured during reporter init TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix`
My suggestion would be to use a different suffix (e.g. "P") and not "Async".

2019-05-17 08:04 UTC, pofider requested changes
I like it. Passing empty string was not obvious and I had several questions regarding that.
I think you just need to fix the mentioned condition and it can be merged.

2019-05-17 08:04 UTC, pofider commented on lib/fileSystemS3.js
> +  if (accessKeyId && secretAccessKey) {
The current solution is to pass accessKeyId as an empty string '' to get the AWS IAM roles auth. To don't break such devs, here should be instead

accessKeyId != null && secretAccessKey != null

2019-05-17 08:04 UTC, pofider commented on lib/fileSystemS3.js
> +        if (accessKeyId && secretAccessKey) {
Same here

2019-06-11 09:26 UTC, merged

2019-06-11 09:26 UTC, pofider commented
I will merge this and do the proposed changes myself.
Thank you for the PR.

2019-06-11 10:12 UTC, cachenbach commented
Thank you! I am so sorry. We had to deviate at short notice out Sprint goal. But we bought a licence for jsreport and will continue to work with jsreport soon. Thanks again!